name: Create Releases
run-name: ${{ github.actor }} is creating a release
on: [push]
jobs:
  Build-Server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v5
      - with:
        go-version: '1.24.2'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build .
